# Generated by Django 4.1.3 on 2024-07-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_name', models.CharField(max_length=400)),
                ('artticles_site', models.CharField(max_length=400)),
            ],
        ),
    ]
