# Generated by Django 4.1.3 on 2024-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_student_detials_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
