# Generated by Django 4.1.3 on 2024-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_student_student_detials_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_id', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_detials',
        ),
    ]
