# Generated by Django 4.1.3 on 2024-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_detials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
