# Generated by Django 4.1.3 on 2024-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student_detials_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detials',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
