# Generated by Django 4.1 on 2024-09-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_market_bedroomdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroomdata',
            name='median_rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
